=== howard1980/Genealogy/Source/Service/appService/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/genealogy/WEB-INF/classes/systemContext.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT beans (bean*)>
<!ELEMENT bean (constructor-arg*,property*)>
<!ATTLIST bean
  name CDATA #REQUIRED
  type CDATA #REQUIRED
  scope (prototype|singleton) #IMPLIED
>
<!ELEMENT constructor-arg EMPTY>
<!ATTLIST constructor-arg
   value CDATA #IMPLIED
   ref CDATA #IMPLIED
>
<!ELEMENT property EMPTY>
<!ATTLIST property
   name CDATA #IMPLIED
   property CDATA #IMPLIED
   ref CDATA #IMPLIED
>

=== howard1980/Genealogy/Source/Service/appService/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/genealogy/WEB-INF/classes/systemContext.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE log4j:configuration SYSTEM "systemContext.dtd">

<beans>
	<!-- BeanFactory実装クラスの名前の定義 -->
	<bean name="beanFactoryImplementClassName" type="java.lang.String">
		<constructor-arg value="com.maxiaohua.genealogy.fw.core.bean.impl.BeanFactoryImpl" />
	</bean>

	<!-- Mybatis関連定義 -->
	<bean name="mybatisConfigFileName" type="java.lang.String">
		<constructor-arg value="mybatis-config.xml" />
	</bean>
	<bean name="envIdProduct" type="java.lang.String">
		<constructor-arg value="product" />
	</bean>
	<bean name="envIdRefer" type="java.lang.String">
		<constructor-arg value="refer" />
	</bean>
	<bean name="environmentIds" type="java.util.ArrayList" scope="singleton">
		<property value="product" />
		<property value="refer" />
	</bean>
	<bean name="packageNames" type="java.util.ArrayList" scope="singleton">
		<property value="com.maxiaohua.genealogy." />
	</bean>
	<bean name="cisSqlSessionFactory" type="com.maxiaohua.genealogy.fw.core.dao.mybatis.ex.CISSqlSessionFactoryImpl" scope="singleton">
		<property name="environmentIds" ref="environmentIds"/>
		<property name="configFileName" ref="mybatisConfigFileName"/>
	</bean>

	<!-- ファイル関連定義 -->
	<bean name="defaultFileConstraint" type="com.maxiaohua.genealogy.fw.core.file.FileConstraint" scope="singleton">
	</bean>
	<bean name="fileConstraints" type="java.util.ArrayList" scope="singleton">
		<property ref="defaultFileConstraint" />
	</bean>

	<!-- 共通DAOの定義 -->
	<bean name="queryDAO" type="com.maxiaohua.genealogy.fw.core.dao.impl.QueryDAOImpl" scope="singleton"/>
	<bean name="updateDAO" type="com.maxiaohua.genealogy.fw.core.dao.impl.UpdateDAOImpl" scope="singleton"/>
	
	<!-- redis用DAO定义 -->
	<bean name="queryKeyValue" type="com.maxiaohua.genealogy.fw.core.memory.db.impl.QueryKeyValueImpl" scope="singleton"/>
	<bean name="updateKeyValue" type="com.maxiaohua.genealogy.fw.core.memory.db.impl.UpdateKeyValueImpl" scope="singleton"/>

	
	<!-- SMS用类定义 -->
	<bean name="sMSManger" type="com.maxiaohua.genealogy.fw.core.sms.impl.SMSManagerImpl" scope="singleton"/>
	
	<!-- JPUSH用类定义 -->
	<bean name="jpushManager" type="com.maxiaohua.genealogy.fw.core.push.impl.JPushManagerImpl" scope="singleton"/>
	
	<!-- 微信支付用类定义 -->
	<bean name="wechetPay" type="com.maxiaohua.genealogy.fw.core.wechet.impl.WechetPayImpl" scope="singleton"/>

	<!-- トランゼクションマネジャーの定義 -->
	<bean name="transactionManager" type="com.maxiaohua.genealogy.fw.core.transaction.impl.TransactionManagerImpl" scope="singleton" />

	<!-- 例外処理クラスの定義 -->
	<bean name="validationExceptionHandler" type="com.maxiaohua.genealogy.fw.core.exception.impl.ValidationExceptionHandlerImpl" scope="singleton" />
	<bean name="applicationExceptionHandler" type="com.maxiaohua.genealogy.fw.core.exception.impl.ApplicationExceptionHandlerImpl" scope="singleton" />
	<bean name="systemExceptionHandler" type="com.maxiaohua.genealogy.fw.core.exception.impl.SystemExceptionHandlerImpl" scope="singleton" />
	<bean name="defaultExceptionHandler" type="com.maxiaohua.genealogy.fw.core.exception.impl.DefaultExceptionHandlerImpl" scope="singleton" />

	<!-- システムハンドルの定義 -->
	<bean name="systemHandler" type="com.maxiaohua.genealogy.fw.core.sys.impl.SystemHandlerImpl" scope="singleton" />

	<!-- メッセージリソースの定義 -->
	<bean name="messageProperties" type="com.maxiaohua.genealogy.fw.core.properties.impl.MessageXMLImpl" scope="singleton">
		<constructor-arg value="message/HbMessageCode" />
	</bean>
	<bean name="serviceMappingProperties" type="com.maxiaohua.genealogy.fw.core.properties.impl.MessagePropertiesImpl" scope="singleton">
		<constructor-arg value="serviceMapping" />
	</bean>
	<bean name="domainMappingProperties" type="com.maxiaohua.genealogy.fw.core.properties.impl.MessagePropertiesImpl" scope="singleton">
		<constructor-arg value="domainMapping" />
	</bean>
	<bean name="commonConfigproperties" type="com.maxiaohua.genealogy.fw.core.properties.impl.MessagePropertiesImpl" scope="singleton">
		<constructor-arg value="commonConfig" />
	</bean>


	<!-- サービスインターセプターチェーンの定義 -->
	<bean name="ajaxParser" type="com.maxiaohua.genealogy.fw.core.ajax.impl.JSONParserImpl" scope="singleton" >
		<property name="packageNames" ref="packageNames"/>
	</bean>
	<bean name="ajaxRender" type="com.maxiaohua.genealogy.fw.core.ajax.impl.JSONRenderImpl" scope="singleton" >
		<property name="packageNames" ref="packageNames"/>
	</bean>
	<bean name="contextSessionControlInterceptor" type="com.maxiaohua.genealogy.fw.web.interceptor.impl.ContextSessionControlInterceptor" scope="singleton" />
	<bean name="sqlSessionControlInterceptor" type="com.maxiaohua.genealogy.fw.web.interceptor.impl.SqlSessionControlInterceptor" scope="singleton" >
		<property name="connectionManager" ref="connectionManager"/>
	</bean>
	<bean name="serviceInputParamInterceptor" type="com.maxiaohua.genealogy.fw.web.interceptor.impl.ServiceInputParamInterceptor" scope="singleton">
		<property name="ajaxParser" ref="ajaxParser"/>
		<property name="ajaxRender" ref="ajaxRender"/>
	</bean>
	<bean name="serviceInterceptor" type="com.maxiaohua.genealogy.fw.web.interceptor.impl.ServiceInterceptor" scope="singleton">
		<property name="transactionManager" ref="transactionManager"/>
	</bean>
	<bean name="serviceOutputParamInterceptor" type="com.maxiaohua.genealogy.fw.web.interceptor.impl.ServiceOutputParamInterceptor" scope="singleton">
		<property name="ajaxRender" ref="ajaxRender"/>
	</bean>
	<bean name="ldapInterceptor" type="com.maxiaohua.genealogy.fw.web.interceptor.impl.LDAPInterceptor" scope="singleton" >
		<property name="ldapFactory" ref="ldapFactory"/>
	</bean>
	<bean name="wechetPayControlInterceptor" type="com.maxiaohua.genealogy.fw.web.interceptor.impl.WechetPayControlInterceptor" scope="singleton" />
	<bean name="interceptors" type="java.util.ArrayList" scope="singleton">
		<property ref="wechetPayControlInterceptor"/>
		<property ref="contextSessionControlInterceptor"/>
		<property ref="sqlSessionControlInterceptor"/>
		<property ref="ldapInterceptor"/>
		<property ref="serviceInputParamInterceptor"/>
		<property ref="serviceInterceptor"/>
		<property ref="serviceOutputParamInterceptor"/>
		
	</bean>
	<bean name="exceptionHandlers" type="java.util.HashMap" scope="singleton">
		<property name="com.maxiaohua.genealogy.fw.core.exception.ValidationException" ref="validationExceptionHandler"/>
		<property name="com.maxiaohua.genealogy.fw.core.exception.ApplicationException" ref="applicationExceptionHandler"/>
		<property name="com.maxiaohua.genealogy.fw.core.exception.SystemException" ref="systemExceptionHandler"/>
		<property name="java.lang.Exception" ref="defaultExceptionHandler"/>
	</bean>
	<bean name="webServiceInterceptorChain" type="com.maxiaohua.genealogy.fw.web.interceptor.impl.CISInterceptorChain" scope="prototype">
		<property name="interceptors" ref="interceptors"/>
		<property name="exceptionHandlers" ref="exceptionHandlers"/>
		<property name="ajaxRender" ref="ajaxRender"/>
		<property name="connectionManager" ref="connectionManager"/>
	</bean>

	<bean name="ldapFactory" type="com.maxiaohua.genealogy.main.biz.com.impl.HbLDAPFactoryImpl" scope="singleton">
		<property name="root" value="dc=cisp,dc=com"/>
		<property name="ldapHostIP" value="127.0.0.1"/>
		<property name="adminPassword" value="password"/>
	</bean>

	<bean name="connectionManager" type="com.maxiaohua.genealogy.fw.core.connection.impl.ConnectionManagerImpl" scope="singleton">
		<property name="retryTimeout" value="10"/>
		<property name="retryCount" value="5"/>
		<property name="validFlg" value="false"/>
		<property name="targetException" value="java.net.SocketException"/>
		<property name="cisSqlSessionFactory" ref="cisSqlSessionFactory"/>
	</bean>

</beans>
